### ISSUE TITLE
Improve the schema guidelines

### ISSUE THREAD

**Issue by mindrones** [nestauk/beis-indicators#134]
We need to add some guidelines to address special/corner cases, as comments in `data/schema/schema_template.yaml` where it applies/works or in a new file `data/schema/README.md`.

(more to add)

### `short_description`

We need to have short descriptions to be used in the sidebar (or in some equivalent menu to navigate through datasets).

<details>
<summary>Sidebar mock up</summary>
<img width="243" alt="Screenshot 2020-02-14 at 18 02 19" src="https://user-images.githubusercontent.com/1309648/74555813-74952500-4f54-11ea-9b2e-81d689144fff.png">
</details>

### Endpoints

The distinction between `endpoint_source` and `endpoint_static` seemed confusing, so we could merge them into `endpoint_url`.

### Derived indicators

These are obtained from other indicators hence some fields of their schema has to reference fields in other schemas. For these, a tentative approach would be the following:

```yaml
api:
  - @ashe_nuts_2_sci_tech.api
  - @nuts_house_prices.api
api_documentation:
  - @ashe_nuts_2_sci_tech.api_documentation
  - @nuts_house_prices.api_documentation
enpoint:
  - @ashe_nuts_2_sci_tech.enpoint
  - @nuts_house_prices.enpoint
source:
  - @ashe_nuts_2_sci_tech.source
  - @nuts_house_prices.source
```

so that a parser can use `@` to distinguish actual values from references to values in other datasets definitions.

We should also use `is_derived_indicator` to be explicit.

### Stripping the tracking token on links

We should do this always. For example this should be removed from the link:
```
?utm_medium=GOV.UK&utm_source=datadownload&utm_campaign=full_fil&utm_term=9.30_16_10_19
```

Taking care of not removing query parameters used by the endpoint to serve the dataset.

### LEP

These should temporarily be placed in a `LEP/` directory for the time being as we won't have a chance to visualise them so that we can fetch all files in `processed/<dir>/*.yaml` assuming they're NUTS2.

### Better documentation

- [x] Some fields in `data/schema/schema_template.yaml` are a bit misleading so we might want to address them.
- [x] explain optional fields
- [x] we have discussed about providing a Latex string for units to be used in papers.

**Comment by mindrones** [comment]
While writing this doc I realised it would be easier to just use:

```yaml
derived_from:
  - ashe_nuts_2_sci_tech
  - nuts_house_prices
```
although I guess it would be a bit less explicit about the missing fields (provenance fields, that would be found on the base indicators).

**Comment by mindrones** [comment]
Also I think we should move a generic description on the geographic region:

```yaml
region:
  type: string # the region type, e.g. NUTS, LEP, etc
  level: int # OPTIONAL - useful for NUTS
  source_url: URL # url of the boundaries used for reverse geocoding
```

and use generic keys for the geo part of `schema`:

```yaml
schema:
  region_id:
    type: NutsRegion.id
  region_year_spec:
    type: NutsRegion.year_spec
```
